### PR TITLE
Add code linting

### PR DESCRIPTION
**Pull request by parro-it**
Hi, I add code linting to the workflow using [standard](https://github.com/feross/standard).
This is not finished yet, I did little changes to every file, and I did not test it. But I want you to get a feeling of the code style as soon as possible...

I add the linting to the NPM test script, so you'll be able to set-up travis and automatically check style on every PR...

still todo by me on this PR:

* Add .travis.yml
* Add standard badge to readme.md
* Do some extensive test

and once this had landed on master, you'll have to enable the repo on your travis account

### CODE REVIEW

**Comment by parro-it** [comment]
Uhm, one of the commit has a comment a little weird :smile:, it should have been "converted source code to `standard` style", but the backtick had inserted output from standard comment...

**Comment by parro-it** [comment]
By the way, I discover `packager.js` and `webpack.config.js` are not checked and they actually fails linting, I will correct this

**Comment by Thomas101** [comment]
Looks like it works! Thanks! xD

**Comment by parro-it** [comment]
Your very welcome!

**Pull request merged**
