### PR TITLE
Added option to toggle the menu bar with Ctrl+\

### PR DESCRIPTION
**Pull request by jamesbvaughan**
I'm pretty new to this as this is my first pull request. Let me know if there's anything I should do differently!

### CODE REVIEW

**Comment by jamesbvaughan** [comment]
I'm pretty new to this as this is my first pull request. Let me know if there's anything I should do differently!

**Comment by Thomas101** [comment]
Awesome! Does linux persist this across sessions? I'll merge it over the next week or so when I get a chance to do some work on 1.2.2. Thank you!!

**Comment by jamesbvaughan** [comment]
Right now, it's not persistent; the menu is visible every time you open the app, but I would also prefer that it be persistent. I'll work on that tomorrow.

**Comment by Thomas101** [comment]
Awesome thanks! Maybe take a look at the way the default download location is done. It's a bit fiddly because the app storage sits in the render thread but has to expose it to the main thread.

Main thread getters can be put here. The data that's stored in settings is auto updated and made available.
https://github.com/Thomas101/wmail/blob/master/src/main/AppSettings.js

The data resides in the alt stores...
https://github.com/Thomas101/wmail/blob/master/src/mailbox/stores/settings/settingsActions.js
https://github.com/Thomas101/wmail/blob/master/src/mailbox/stores/settings/settingsStore.js

I'd be happy to put this in when I merge it though. Will only take me 10 minutes

**Comment by jamesbvaughan** [comment]
That sounds good! I'll give it a shot if I have time in the next couple of days, but if that puts you behind schedule at all, then feel free to do it.

**Pull request merged**
