### PR TITLE
Initial windows platform implementation

### PR DESCRIPTION
**Pull request by MarshallOfSound**
**DONE**  
* Fixed settings storage with mkdirp
* Added double click tray event
* Added packer commands

**TODO**
* [x] Implement [electron-winstaller](https://github.com/electron/windows-installer) for single `.exe` packaging
* [ ] Appveyor CI? *Requires admin on repo to trigger and setup*

RE: #101

### CODE REVIEW

**Comment by locly** [comment]
Awesome! Thanks! I'll get this merged in over the weekend and hopefully push out a new version of wmail with windows support! Thank you :)

**Comment by Thomas101** [comment]
Awesome! Thanks! I'll get this merged in over the weekend and hopefully push out a new version of wmail with windows support! Thank you :)

**Comment by Thomas101** [comment]
Hi @MarshallOfSound. I've got the windows version building, but having some trouble with the installer. I was wondering if you had any issues?

I've done...
```
brew install wine
brew install mono
DEBUG=electron-windows-installer:main node packager.js win32 #to get some debug info, otherwise npm run-script package:win32
```

and I end up with the following....

```
[START] Electron Winstaller
  electron-windows-installer:main Using Mono: 'mono' +0ms
  electron-windows-installer:main Using Wine: 'wine' +3ms
  electron-windows-installer:main Created NuSpec file:
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>wmail</id>
    <title>wmail</title>
    <version>1.2.4</version>
    <authors>Thomas Beverley</authors>
    <owners>Thomas Beverley</owners>
    <iconUrl>https://raw.githubusercontent.com/atom/electron/master/atom/browser/resources/win/atom.ico</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>The missing desktop client for Gmail &amp; Google Inbox</description>
    <copyright>Copyright © 2016 Thomas Beverley</copyright>
  </metadata>
  <files>
    <file src="locales/**" target="lib/net45/locales" />
    <file src="resources/**" target="lib/net45/resources" />
    <file src="*.bin" target="lib/net45" />
    <file src="*.dll" target="lib/net45" />
    <file src="*.pak" target="lib/net45" />
    <file src="Update.exe" target="lib/net45/squirrel.exe" />
    <file src="icudtl.dat" target="lib/net45/icudtl.dat" />
    <file src="LICENSE" target="lib/net45/LICENSE" />
    <file src="wmail.exe" target="lib/net45/wmail.exe" />
  </files>
</package>
 +7s
[Error: Failed with exit code: 1
Output:
Attempting to build package from 'wmail.nuspec'.
An error occurred while parsing EntityName. Line 1, position 39.
]
```

**Comment by MarshallOfSound** [comment]
@Thomas101 Building for windows on non-windows platforms has always had strange issues.

I would recommend setting up an automated build on http://www.appveyor.com and raise an issue over at https://github.com/electron-userland/electron-packager/issues

**Comment by Thomas101** [comment]
Okay, thanks for the advice. I've already raised an issue. I'll take a look at appveyor or maybe setup the build environment on my windows vm. Thanks!

**Pull request merged**
