### PR TITLE
#499: Add Goolge Hangouts Service

### PR DESCRIPTION
**Pull request by inikolaev**
This PR adds a simple Google Hangouts service tab implementation similar to that of Calendar.

I didn't really know how to call this service in a generic way but thought that `COMMUNICATION` suits this purpose well.

I added icons of different sizes, though I noticed that we only use icons of 128px size, but that should be optimized in the future.

### CODE REVIEW

**Comment by Thomas101** [comment]
Hi, thanks for adding this in! Sorry I've not had a chance to merge it in yet. I've been working on something for the next release and will make sure this gets added in :)

**Comment by inikolaev** [comment]
No worries, I still plan to made more changes to make it complete from my point of view when I have time.

**Comment by Thomas101** [comment]
Hi, Sorry for being tardy on this. Looking to merge this into the project. I've updated the [Contributing guidelines](https://github.com/Thomas101/wmail/blob/master/CONTRIBUTING.md#pull-requests) for pull requests to ensure they are made under the projects MPL-2.0 license. Are you still okay for me to merge this in?

**Comment by inikolaev** [comment]
Hi, it's ok to merge it. There're some more improvements to be made, but this is a good start I think.

**Comment by Thomas101** [comment]
Thanks!

**Pull request merged**
