### PR TITLE
When selecting to download an update, open the releases page instead of the homepage

### PR DESCRIPTION
**Pull request by vitorgalvao**
This seems like a better experience, to me. Least amount of effort to the user.

### CODE REVIEW

**Comment by Thomas101** [comment]
Thanks!

**Comment by paulyoung** [comment]
When does this get run? I was previously using 1.1.7 and didn't see any prompts for newer versions, and couldn't find anything like "Check for updates" in the UI.

**Comment by Thomas101** [comment]
Hi Paul it's run on app launch

**Comment by paulyoung** [comment]
Ah – I don't think I've quit the app since I installed it!

**Pull request merged**
